### ISSUE TITLE
Tried to copy contents of templates /assets folder but the folder does not exist! 

### ISSUE THREAD

**Issue by ghost** [Zedelghem/pystatic#1]
I cloned the repo and set up a basic demo of the app. I found one glitch while setting up. 

During set up, I ran into this error message when running build.py for the first time:

(ENV) ➜  pystatic git:(master) ✗ python build.py
Tried to copy contents of templates /assets folder but the folder does not exist! Make one, even empty!

I was able to debug simply by tracing pystatic.py to line 249, where it  appears a forward slash is missing from the path concatenation. Fixed locally as follows:

```
    try:
        copytree(css_and_assets_path + "assets", "site/assets")
    except:
        print("Tried to copy contents of", css_and_assets_path, "/assets folder but the folder does not exist! Make one, even empty!")
```

should have a slash before assets, otherwise build.py doesn't find the assets folder

```
try:
        copytree(css_and_assets_path + "/assets", "site/assets")
    except:
        print("Tried to copy contents of", css_and_assets_path, "/assets folder but the folder does not exist! Make one, even empty!")
```

**Comment by Zedelghem** [comment]
Hi Alex,

Thanks for the heads up! Just fixed it.

I am really happy someone gave pystatic a try! ;)
