### ISSUE TITLE
POSSIBLE BUG: CONFIG file called as config

### ISSUE THREAD

**Issue by ghost** [Zedelghem/pystatic#5]
When testing out the recently added (and very spiffy) CONFIG file, I had a small issue where build.py was not able to locate CONFIG. This appears to be a simple case sensitivity issue, where CONFIG could be renamed lower case 'config'. Conversely, the script could call upper case CONFIG for file input.

Steps to reproduce:
- Install, configure and prepare to run pystatic
- Execute ```python build.py```
- Observe error like:

user:$ python build.py 
Traceback (most recent call last):
  File "build.py", line 36, in <module>
    build_website(parse_config("config")[0], **parse_config("config")[1])
  File "/devpath/to/pystatic/pystatic.py", line 227, in parse_config
    cfg_file = open(filename, "r")
FileNotFoundError: [Errno 2] No such file or directory: 'config'

**Comment by ghost** [comment]
Offered pull request as a simple fix or workaround for this:
https://github.com/Zedelghem/pystatic/pull/6
https://github.com/Zedelghem/pystatic/pull/6.diff

**Comment by Zedelghem** [comment]
Thanks, merged and closed!
