### ISSUE TITLE
Missing templates/lib directory on initial build 

### ISSUE THREAD

**Issue by ghost** [Zedelghem/pystatic#7]
On initial checkout of repo and first use, I encountered this error message:

```
user@dev:~/develoment_dir/pystatic$ python build.py
Tried to copy contents of templates /lib folder but the folder does not exist! Make one, even empty!
```

Appears that templates/lib needs to be created by user, simple enough. Is there any reason this directory can not be included as part of the standard directory structure? It is shown in the README as part of the intended initial file structure:

```
|- pystatic.py
|- build.py
|- CONFIG
|- LICENSE
|-
|- templates/
|-- index.html
|-- post.html
|-- css/
|--- style.css
|-- lib/
|--- (empty by default) any additional scripts you might need
|-- assets/
|--- (empty by default) whatever additional files you need
|--- ...
|-
|- posts/
|-- 2018-03-12_best_title.md
|-- ...
|
|- site/
|-- index.html
|-- posts/
|--- 2018-03-12_best_title.html
|--- ...
|-- css/
|--- style.css
|-- assets/
|-- lib/
```

**Comment by Zedelghem** [comment]
Thanks for noticing that. I took the dirty way and included an empty scripts.js file.

**Comment by Zedelghem** [comment]
I figured there was one line missing in the function that populated directories. Now we can have an empty lib folder.
